from datetime import datetime


def build_markdown_report(gene: str, disease: str, results: dict) -> str:
    ts = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines = [
        f"# 🧬 BioPilot AI — Research Report",
        f"**Gene/lncRNA:** {gene}  |  **Disease:** {disease}  |  **Generated:** {ts}",
        f"\n---\n",
    ]
    labels = {
        "orchestrator": "🧠 Research Orchestrator",
        "gene":         "🔬 Gene Intelligence",
        "literature":   "📚 Literature Intelligence",
        "pathway":      "🌐 Pathway & Network",
        "hypothesis":   "💡 Hypothesis Generator",
        "experiment":   "🧪 Experimental Design",
        "report":       "📝 Scientific Report",
    }
    for key, label in labels.items():
        if key in results:
            lines.append(f"## {label}\n\n{results[key]}\n\n---\n")
    lines.append("\n*Generated by BioPilot AI · Microsoft Agents League Hackathon 2026*")
    return "\n".join(lines)


def build_txt_report(gene: str, disease: str, results: dict) -> str:
    return build_markdown_report(gene, disease, results).replace("**", "").replace("##", "==").replace("#", "=")